/** @type {import('tailwindcss').Config} */
export default {
	content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
	plugins: [require("@tailwindcss/typography"), require("daisyui")],
	daisyui: {
		themes: [
			"dark",
			// "dark",
			// "cupcake",
			// "bumblebee",
			// "emerald",
			// "corporate",
			// "synthwave",
			// "retro",
			// "cyberpunk",
			// "valentine",
			// "halloween",
			// "garden",
			// "forest",
			// "aqua",
			// "lofi",
			// "pastel",
			// "fantasy",
			// "wireframe",
			// "black",
			// "luxury",
			// "dracula",
			// "cmyk",
			// "autumn",
			// "business",
			// "acid",
			// "lemonade",
			// "night",
			// "coffee",
			// "winter",
		],
	},
};
